title: Nikoleta E. Glynatsi
email: GlynatsiNE@cardiff.ac.uk
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/talks" # the subpath of your site, e.g. /blog
url: ""
twitter_username: NikoletaGlyn
github_username:  Nikoleta-v3
plus_username: "+NikoletaGlynatsi"

# Build settings
markdown: kramdown
theme: minima
sass:
  sass_dir: _sass
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
include: ['_pages']
